name: Build
on: [push]
jobs:
  build:
    runs-on: macos-12

    steps:
    - run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
    - run: |
        softwareupdate --list
        xcodebuild --help
      name: Investigate
      
    - run: |
        softwareupdate --list
        xcrun --show-sdk-path --sdk macosx
      name: Repro
      
    - run: |        
        sudo rm -rf /Library/Developer/CommandLineTools
        xcode-select --install
        xcrun --show-sdk-path --sdk macosx
      name: Fix
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test back and forth
