name: Build
on: [push]
jobs:
  repro:
    runs-on: macos-12
    steps:
    - run: |
        softwareupdate --list
        ls -la /Applications|grep Xcode
      name: Investigate  
    - run: |
        softwareupdate --list
        xcrun --show-sdk-path --sdk macosx
      name: Repro
      
  rm-commandlinetools:
    if: ${{ true }}
    runs-on: macos-12

    steps:
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sudo rm -rf /Library/Developer/CommandLineTools
        xcode-select --install
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        sudo rm -rf /Library/Developer/CommandLineTools
        xcode-select --install
      name: Fix
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.2.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.3.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.4.1
      
  softwareupdate-install:
    if: ${{ true }}
    runs-on: macos-12

    steps:
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        softwareupdate --install
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        softwareupdate --install
      name: Fix
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.2.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.3.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.4.1
      
  selects:
    if: ${{ true }}
    runs-on: macos-12

    steps:
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      name: Fix
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.2.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.3.1
          
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.4.1
      
  dry-runs:
    if: ${{ true }}
    runs-on: macos-12

    steps:
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
      name: Fix
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.2.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.3.1
          
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.4.1
  
      
  time-out:
    if: ${{ true }}
    runs-on: macos-12

    steps:
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        sleep 5
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        sleep 5
      name: Fix

    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.2.1
      
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.3.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.3.1
      
        
    - run: |        
        sudo xcode-select --switch /Applications/Xcode_13.4.1.app
        xcrun --show-sdk-path --sdk macosx
      name: Test 13.4.1
