name: Build
on: [push]
jobs:
  build:
    runs-on: macos-12

    steps:
    - run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
    - run: |
        softwareupdate --list
        xcodebuild --help
        xcrun --show-sdk-path --sdk macosx
