name: Build
on: [push]
jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - run: sudo xcode-select --switch /Applications/Xcode_13.3.1.app
    - run: cmake .
    - run: cmake --build . --verbose